# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          pip install ruff
          ruff check .
      - name: Run unit tests
        run: |
          pip install pytest
          pytest -q
      - name: Train model (dry-run)
        run: |
          python -c "from src.data import download_data,load_raw,clean_and_preprocess; p=download_data(); df=clean_and_preprocess(load_raw(p))"
          python src/train.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            models/final_model.joblib
            models/metrics.csv
